services:
  flask:
    env_file:
      - ./.env.ci
    volumes:
      - ./tests/resources/biorxiv:/app/biorxiv
      - ./tests/resources/mecadoi:/app/mecadoi

  neo4j:
    env_file:
      - ./.env.ci
    volumes:
      - ./tests/data/neo4j-data:/data
