version: '3'

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: neoflask_local_flask
    depends_on:
      - neo4j
      - redis
    volumes:
      - .:/app
      - ./log:/log
      - ${BIORXIV_PATH}:/app/biorxiv # to be provided in .env
      - ${MECADOI_PATH}:/app/mecadoi
    env_file:
      - ./.env
    shm_size: '16gb'
    command: /start

  neo4j:
    image: neo4j:4.1
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - ./data/neo4j-data:/data
      - ./data/neo4j-logs:/logs
      - ./data/neo4j-plugins:/plugins
    env_file:
      - ./.env

  redis:
    image: redis:6
    volumes:
      - ./data/redis-data:/data
