version: '3'

volumes:
  flask-logs:
  neo4j-data:
  neo4j-logs:
  neo4j-plugins:
  redis-data:

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: neoflask_local_flask
    depends_on:
      - neo4j
      - redis
    volumes:
      - .:/app
      - flask-logs:/log
      - ${BIORXIV_PATH}:/app/biorxiv # to be provided in .env
      - ${MECADOI_PATH}:/app/mecadoi
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /tmp:/tmp
    environment:
      - XAUTHORITY=${XAUTH} # needs to make sure export XAUTH before i.e. in .bashrc
      - DISPLAY=${DISPLAY} # this seems to be exported by default 
    env_file:
      - ./.env
    shm_size: '16gb'
    command: /start

  neo4j:
    image: neo4j:4.1
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-plugins:/plugins
    env_file:
      - ./.env

  redis:
    image: redis:6
    volumes:
      - redis-data:/data
