# This file is used by the CI system (Github Actions) to build four of the five images that comprise the production
# system as defined in production.yml (the other one uses a plain, pre-built image).
# They are stored in the Github Container Registry under the image tag specified here. See the Github Actions workflow
# definition for information on the environment variables used here.
services:
  flask:
    image: ghcr.io/source-data/sd-graph_flask:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}

  neo4j:
    image: ghcr.io/source-data/sd-graph_neo4j:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/neo4j/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}

  traefik:
    image: ghcr.io/source-data/sd-graph_traefik:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}

  vuejs:
    image: ghcr.io/source-data/sd-graph_vuejs:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/vuejs/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}
