version: '3'

services:
  flask:
    image: ghcr.io/source-data/sd-graph_deploy_flask:${IMAGE_TAG}
    depends_on:
      - neo4j
      - redis
    volumes:
      - .:/app
      - ./log:/log
      - ${BIORXIV_PATH}:/app/biorxiv # to be provided in .env
      - ${MECADOI_PATH}:/app/mecadoi
    env_file:
      - ./.env
    shm_size: '16gb'
    command: /start
    working_dir: /app

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - ./data/neo4j-data:/data
      - ./data/neo4j-logs:/logs
      - ./data/neo4j-plugins:/plugins
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: ${NEO4J_MEMORY_LIMIT:-4G}

  redis:
    image: redis:6
    volumes:
      - ./data/redis-data:/data
