# This file is used by the CI system (Github Actions) to build three of the five images
# that comprise the production system as defined in production.yml as well as one of the
# images used during database updating (the other services use plain, pre-built images).
# They are stored in the Github Container Registry under the image tag specified here.
# See the Github Actions workflow for information on the environment variables used here.
version: '3'
services:
  flask_deploy:
    image: ghcr.io/source-data/sd-graph_deploy_flask:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    labels:
      org.opencontainers.image.source: ${IMAGE_SOURCE}
      org.opencontainers.image.revision: ${IMAGE_REVISION}

  flask:
    image: ghcr.io/source-data/sd-graph_flask:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}

  traefik:
    image: ghcr.io/source-data/sd-graph_traefik:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}

  vuejs:
    image: ghcr.io/source-data/sd-graph_vuejs:${IMAGE_TAG}
    build:
      context: .
      dockerfile: ./compose/production/vuejs/Dockerfile
      labels:
        org.opencontainers.image.source: ${IMAGE_SOURCE}
        org.opencontainers.image.revision: ${IMAGE_REVISION}
