version: '3'

volumes:
  production_neo4j_data: {}
  production_neo4j_logs: {}
  production_traefik: {}
  production_redis: {}

services:
  flask:
    build:
      context: .
      dockerfile: ./compose/production/flask/Dockerfile
    image: neoflask_production_flask
    depends_on:
      - neo4j
    env_file:
      - ./.env
    shm_size: '16gb'
    # ports:
    #   - "5000:5000"
    command: /start

  neo4j:
    image: neo4j:3.5
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - production_neo4j_data:/data
      - production_neo4j_logs:/logs
    env_file:
      - ./.env
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: neoflask_production_traefik
    depends_on:
      - flask
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      # - "8080:8080" # debugging UI
      - "0.0.0.0:443:443"
  vuejs:
    build:
      context: .
      dockerfile: ./compose/production/vuejs/Dockerfile
    image: neoflask_production_vuejs
    env_file:
      - ./.env
    # ports:
    #   - "9080:80"

  redis:
    image: redis:6
    volumes:
      - production_redis:/data
