version: '3'

volumes:
  production_flask_logs: {}
  production_neo4j_data: {}
  production_neo4j_logs: {}
  production_traefik: {}
  production_traefik_logs: {}
  production_redis: {}

services:
  flask:
    image: ghcr.io/source-data/sd-graph_flask:${IMAGE_TAG}
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - production_flask_logs:/app/log
    env_file:
      - ./.env
    shm_size: '16gb'
    command: /runserver

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - production_neo4j_data:/data
      - production_neo4j_logs:/logs
    env_file:
      - ./.env
    healthcheck:
      test: cypher-shell -u ${NEO_USERNAME} -p ${NEO_PASSWORD} --non-interactive "MATCH (n) RETURN ID(n) LIMIT 1"
      # wait up to 10 minutes for neo4j to be ready
      interval: 10s
      timeout: 10s
      retries: 60

  traefik:
    image: ghcr.io/source-data/sd-graph_traefik:${IMAGE_TAG}
    depends_on:
      - flask
    env_file: .env
    volumes:
      - production_traefik:/etc/traefik/acme
      - production_traefik_logs:/var/log/traefik
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  vuejs:
    image: ghcr.io/source-data/sd-graph_vuejs:${IMAGE_TAG}
    depends_on: 
      - flask
    env_file:
      - ./.env

  redis:
    image: redis:6
    healthcheck:
      test: redis-cli --raw incr ping
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    volumes:
      - production_redis:/data
