version: '3'

volumes:
  production_flask_logs: {}
  production_neo4j_data: {}
  production_neo4j_logs: {}
  production_traefik: {}
  production_traefik_logs: {}
  production_redis: {}

services:
  flask:
    image: ghcr.io/source-data/sd-graph_flask:${IMAGE_TAG}
    depends_on:
      - neo4j
    volumes:
      - production_flask_logs:/app/log
    env_file:
      - ./.env
    shm_size: '16gb'
    # ports:
    #   - "5000:5000"
    command: /start

  neo4j:
    image: neo4j:4.4
    environment:
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    volumes:
      - production_neo4j_data:/data
      - production_neo4j_logs:/logs
    env_file:
      - ./.env
    # ports:
    #   - "7474:7474"
    #   - "7687:7687"

  traefik:
    image: ghcr.io/source-data/sd-graph_traefik:${IMAGE_TAG}
    depends_on:
      - flask
    env_file: .env
    volumes:
      - production_traefik:/etc/traefik/acme
      - production_traefik_logs:/var/log/traefik
    ports:
      - "0.0.0.0:80:80"
      # - "8080:8080" # debugging UI
      - "0.0.0.0:443:443"

  vuejs:
    image: ghcr.io/source-data/sd-graph_vuejs:${IMAGE_TAG}
    depends_on: 
      - flask
    env_file:
      - ./.env
    # ports:
    #   - "9080:80"

  redis:
    image: redis:6
    ulimits:
      nofile:
        soft: 12000
        hard: 12000
    volumes:
      - production_redis:/data
