/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Author model module.
 * @module model/Author
 * @version 2.0.0
 */
export class Author {
  /**
   * Constructs a new <code>Author</code>.
   * @alias module:model/Author
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Author</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Author} obj Optional instance to populate.
   * @return {module:model/Author} The populated <code>Author</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Author();
      if (data.hasOwnProperty('surname'))
        obj.surname = ApiClient.convertToType(data['surname'], 'String');
      if (data.hasOwnProperty('corresp'))
        obj.corresp = ApiClient.convertToType(data['corresp'], 'String');
      if (data.hasOwnProperty('orcid'))
        obj.orcid = ApiClient.convertToType(data['orcid'], 'String');
      if (data.hasOwnProperty('position_idx'))
        obj.positionIdx = ApiClient.convertToType(data['position_idx'], 'Number');
      if (data.hasOwnProperty('given_names'))
        obj.givenNames = ApiClient.convertToType(data['given_names'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} surname
 */
Author.prototype.surname = undefined;

/**
 * @member {String} corresp
 */
Author.prototype.corresp = undefined;

/**
 * @member {String} orcid
 */
Author.prototype.orcid = undefined;

/**
 * @member {Number} positionIdx
 */
Author.prototype.positionIdx = undefined;

/**
 * @member {String} givenNames
 */
Author.prototype.givenNames = undefined;

