/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PagingInfo model module.
 * @module model/PagingInfo
 * @version 2.0.0
 */
export class PagingInfo {
  /**
   * Constructs a new <code>PagingInfo</code>.
   * @alias module:model/PagingInfo
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PagingInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PagingInfo} obj Optional instance to populate.
   * @return {module:model/PagingInfo} The populated <code>PagingInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PagingInfo();
      if (data.hasOwnProperty('first'))
        obj.first = ApiClient.convertToType(data['first'], 'String');
      if (data.hasOwnProperty('prev'))
        obj.prev = ApiClient.convertToType(data['prev'], 'String');
      if (data.hasOwnProperty('current'))
        obj.current = ApiClient.convertToType(data['current'], 'String');
      if (data.hasOwnProperty('next'))
        obj.next = ApiClient.convertToType(data['next'], 'String');
      if (data.hasOwnProperty('last'))
        obj.last = ApiClient.convertToType(data['last'], 'String');
      if (data.hasOwnProperty('currentPage'))
        obj.currentPage = ApiClient.convertToType(data['currentPage'], 'Number');
      if (data.hasOwnProperty('totalPages'))
        obj.totalPages = ApiClient.convertToType(data['totalPages'], 'Number');
      if (data.hasOwnProperty('perPage'))
        obj.perPage = ApiClient.convertToType(data['perPage'], 'Number');
      if (data.hasOwnProperty('totalItems'))
        obj.totalItems = ApiClient.convertToType(data['totalItems'], 'Number');
      if (data.hasOwnProperty('sortedBy'))
        obj.sortedBy = ApiClient.convertToType(data['sortedBy'], 'String');
      if (data.hasOwnProperty('sortedOrder'))
        obj.sortedOrder = ApiClient.convertToType(data['sortedOrder'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} first
 */
PagingInfo.prototype.first = undefined;

/**
 * @member {String} prev
 */
PagingInfo.prototype.prev = undefined;

/**
 * @member {String} current
 */
PagingInfo.prototype.current = undefined;

/**
 * @member {String} next
 */
PagingInfo.prototype.next = undefined;

/**
 * @member {String} last
 */
PagingInfo.prototype.last = undefined;

/**
 * @member {Number} currentPage
 */
PagingInfo.prototype.currentPage = undefined;

/**
 * @member {Number} totalPages
 */
PagingInfo.prototype.totalPages = undefined;

/**
 * @member {Number} perPage
 */
PagingInfo.prototype.perPage = undefined;

/**
 * @member {Number} totalItems
 */
PagingInfo.prototype.totalItems = undefined;

/**
 * @member {String} sortedBy
 */
PagingInfo.prototype.sortedBy = undefined;

/**
 * @member {String} sortedOrder
 */
PagingInfo.prototype.sortedOrder = undefined;

