/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Author} from './Author';

/**
 * The Paper model module.
 * @module model/Paper
 * @version 2.0.0
 */
export class Paper {
  /**
   * Constructs a new <code>Paper</code>.
   * @alias module:model/Paper
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Paper</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Paper} obj Optional instance to populate.
   * @return {module:model/Paper} The populated <code>Paper</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Paper();
      if (data.hasOwnProperty('doi'))
        obj.doi = ApiClient.convertToType(data['doi'], 'String');
      if (data.hasOwnProperty('version'))
        obj.version = ApiClient.convertToType(data['version'], 'String');
      if (data.hasOwnProperty('source'))
        obj.source = ApiClient.convertToType(data['source'], 'String');
      if (data.hasOwnProperty('journal'))
        obj.journal = ApiClient.convertToType(data['journal'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('abstract'))
        obj._abstract = ApiClient.convertToType(data['abstract'], 'String');
      if (data.hasOwnProperty('journal_doi'))
        obj.journalDoi = ApiClient.convertToType(data['journal_doi'], 'String');
      if (data.hasOwnProperty('published_journal_title'))
        obj.publishedJournalTitle = ApiClient.convertToType(data['published_journal_title'], 'String');
      if (data.hasOwnProperty('pub_date'))
        obj.pubDate = ApiClient.convertToType(data['pub_date'], 'Date');
      if (data.hasOwnProperty('authors'))
        obj.authors = ApiClient.convertToType(data['authors'], [Author]);
      if (data.hasOwnProperty('revdate'))
        obj.revdate = ApiClient.convertToType(data['revdate'], 'Date');
      if (data.hasOwnProperty('entities'))
        obj.entities = ApiClient.convertToType(data['entities'], ['String']);
      if (data.hasOwnProperty('assays'))
        obj.assays = ApiClient.convertToType(data['assays'], ['String']);
      if (data.hasOwnProperty('main_topics'))
        obj.mainTopics = ApiClient.convertToType(data['main_topics'], ['String']);
      if (data.hasOwnProperty('highlighted_entities'))
        obj.highlightedEntities = ApiClient.convertToType(data['highlighted_entities'], ['String']);
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('reviewed_by'))
        obj.reviewedBy = ApiClient.convertToType(data['reviewed_by'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} doi
 */
Paper.prototype.doi = undefined;

/**
 * @member {String} version
 */
Paper.prototype.version = undefined;

/**
 * @member {String} source
 */
Paper.prototype.source = undefined;

/**
 * @member {String} journal
 */
Paper.prototype.journal = undefined;

/**
 * @member {String} title
 */
Paper.prototype.title = undefined;

/**
 * @member {String} _abstract
 */
Paper.prototype._abstract = undefined;

/**
 * @member {String} journalDoi
 */
Paper.prototype.journalDoi = undefined;

/**
 * @member {String} publishedJournalTitle
 */
Paper.prototype.publishedJournalTitle = undefined;

/**
 * @member {Date} pubDate
 */
Paper.prototype.pubDate = undefined;

/**
 * @member {Array.<module:model/Author>} authors
 */
Paper.prototype.authors = undefined;

/**
 * @member {Date} revdate
 */
Paper.prototype.revdate = undefined;

/**
 * @member {Array.<String>} entities
 */
Paper.prototype.entities = undefined;

/**
 * @member {Array.<String>} assays
 */
Paper.prototype.assays = undefined;

/**
 * @member {Array.<String>} mainTopics
 */
Paper.prototype.mainTopics = undefined;

/**
 * @member {Array.<String>} highlightedEntities
 */
Paper.prototype.highlightedEntities = undefined;

/**
 * @member {String} slug
 */
Paper.prototype.slug = undefined;

/**
 * @member {Array.<String>} reviewedBy
 */
Paper.prototype.reviewedBy = undefined;

