/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ReviewingServiceCollectionInner} from './ReviewingServiceCollectionInner';

/**
 * The ReviewingServiceCollection model module.
 * @module model/ReviewingServiceCollection
 * @version 2.0.0
 */
export class ReviewingServiceCollection extends Array {
  /**
   * Constructs a new <code>ReviewingServiceCollection</code>.
   * @alias module:model/ReviewingServiceCollection
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>ReviewingServiceCollection</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewingServiceCollection} obj Optional instance to populate.
   * @return {module:model/ReviewingServiceCollection} The populated <code>ReviewingServiceCollection</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewingServiceCollection();
      ApiClient.constructFromObject(data, obj, 'ReviewingServiceCollectionInner');
    }
    return obj;
  }
}
