/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ReviewingServiceDescription} from './ReviewingServiceDescription';

/**
 * The ReviewingServiceCollectionInner model module.
 * @module model/ReviewingServiceCollectionInner
 * @version 2.0.0
 */
export class ReviewingServiceCollectionInner {
  /**
   * Constructs a new <code>ReviewingServiceCollectionInner</code>.
   * @alias module:model/ReviewingServiceCollectionInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReviewingServiceCollectionInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewingServiceCollectionInner} obj Optional instance to populate.
   * @return {module:model/ReviewingServiceCollectionInner} The populated <code>ReviewingServiceCollectionInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewingServiceCollectionInner();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('reviewing_service_description'))
        obj.reviewingServiceDescription = ReviewingServiceDescription.constructFromObject(data['reviewing_service_description']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
ReviewingServiceCollectionInner.prototype.id = undefined;

/**
 * @member {module:model/ReviewingServiceDescription} reviewingServiceDescription
 */
ReviewingServiceCollectionInner.prototype.reviewingServiceDescription = undefined;

