/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReviewingServiceDescription model module.
 * @module model/ReviewingServiceDescription
 * @version 2.0.0
 */
export class ReviewingServiceDescription {
  /**
   * Constructs a new <code>ReviewingServiceDescription</code>.
   * @alias module:model/ReviewingServiceDescription
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReviewingServiceDescription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReviewingServiceDescription} obj Optional instance to populate.
   * @return {module:model/ReviewingServiceDescription} The populated <code>ReviewingServiceDescription</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReviewingServiceDescription();
      if (data.hasOwnProperty('peer_review_policy'))
        obj.peerReviewPolicy = ApiClient.convertToType(data['peer_review_policy'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('competing_interests'))
        obj.competingInterests = ApiClient.convertToType(data['competing_interests'], 'String');
      if (data.hasOwnProperty('opportunity_for_author_response'))
        obj.opportunityForAuthorResponse = ApiClient.convertToType(data['opportunity_for_author_response'], 'String');
      if (data.hasOwnProperty('reviewer_selected_by'))
        obj.reviewerSelectedBy = ApiClient.convertToType(data['reviewer_selected_by'], 'String');
      if (data.hasOwnProperty('recommendation'))
        obj.recommendation = ApiClient.convertToType(data['recommendation'], 'String');
      if (data.hasOwnProperty('public_interaction'))
        obj.publicInteraction = ApiClient.convertToType(data['public_interaction'], 'String');
      if (data.hasOwnProperty('review_coverage'))
        obj.reviewCoverage = ApiClient.convertToType(data['review_coverage'], 'String');
      if (data.hasOwnProperty('review_requested_by'))
        obj.reviewRequestedBy = ApiClient.convertToType(data['review_requested_by'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('reviewer_identity_known_to'))
        obj.reviewerIdentityKnownTo = ApiClient.convertToType(data['reviewer_identity_known_to'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} peerReviewPolicy
 */
ReviewingServiceDescription.prototype.peerReviewPolicy = undefined;

/**
 * @member {String} name
 */
ReviewingServiceDescription.prototype.name = undefined;

/**
 * @member {String} competingInterests
 */
ReviewingServiceDescription.prototype.competingInterests = undefined;

/**
 * @member {String} opportunityForAuthorResponse
 */
ReviewingServiceDescription.prototype.opportunityForAuthorResponse = undefined;

/**
 * @member {String} reviewerSelectedBy
 */
ReviewingServiceDescription.prototype.reviewerSelectedBy = undefined;

/**
 * @member {String} recommendation
 */
ReviewingServiceDescription.prototype.recommendation = undefined;

/**
 * @member {String} publicInteraction
 */
ReviewingServiceDescription.prototype.publicInteraction = undefined;

/**
 * @member {String} reviewCoverage
 */
ReviewingServiceDescription.prototype.reviewCoverage = undefined;

/**
 * @member {String} reviewRequestedBy
 */
ReviewingServiceDescription.prototype.reviewRequestedBy = undefined;

/**
 * @member {String} url
 */
ReviewingServiceDescription.prototype.url = undefined;

/**
 * @member {String} reviewerIdentityKnownTo
 */
ReviewingServiceDescription.prototype.reviewerIdentityKnownTo = undefined;

