# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.paging_info import PagingInfo  # noqa: F401,E501
from swagger_server.models.paper import Paper  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, items: List[Paper]=None, paging: PagingInfo=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param items: The items of this InlineResponse200.  # noqa: E501
        :type items: List[Paper]
        :param paging: The paging of this InlineResponse200.  # noqa: E501
        :type paging: PagingInfo
        """
        self.swagger_types = {
            'items': List[Paper],
            'paging': PagingInfo
        }

        self.attribute_map = {
            'items': 'items',
            'paging': 'paging'
        }
        self._items = items
        self._paging = paging

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def items(self) -> List[Paper]:
        """Gets the items of this InlineResponse200.


        :return: The items of this InlineResponse200.
        :rtype: List[Paper]
        """
        return self._items

    @items.setter
    def items(self, items: List[Paper]):
        """Sets the items of this InlineResponse200.


        :param items: The items of this InlineResponse200.
        :type items: List[Paper]
        """

        self._items = items

    @property
    def paging(self) -> PagingInfo:
        """Gets the paging of this InlineResponse200.


        :return: The paging of this InlineResponse200.
        :rtype: PagingInfo
        """
        return self._paging

    @paging.setter
    def paging(self, paging: PagingInfo):
        """Sets the paging of this InlineResponse200.


        :param paging: The paging of this InlineResponse200.
        :type paging: PagingInfo
        """

        self._paging = paging
