# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SortOrder(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ASC = "asc"
    DESC = "desc"
    def __init__(self):  # noqa: E501
        """SortOrder - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'SortOrder':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SortOrder of this SortOrder.  # noqa: E501
        :rtype: SortOrder
        """
        return util.deserialize_model(dikt, cls)
