/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Author} from './model/Author';
import {InlineResponse200} from './model/InlineResponse200';
import {PagingInfo} from './model/PagingInfo';
import {Paper} from './model/Paper';
import {ReviewingServiceCollection} from './model/ReviewingServiceCollection';
import {ReviewingServiceCollectionInner} from './model/ReviewingServiceCollectionInner';
import {ReviewingServiceDescription} from './model/ReviewingServiceDescription';
import {PaperDetailsApi} from './api/PaperDetailsApi';
import {ReviewingServicesApi} from './api/ReviewingServicesApi';

/**
* Read_only_API_for_the_Early_Evidence_Base_platform_providing_collections_of_papers_by_reviewing_service_automagic_and_auto_topics_as_well_as_details_on_papers_by_DOI_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var EarlyEvidenceBaseApi = require('index'); // See note below*.
* var xxxSvc = new EarlyEvidenceBaseApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new EarlyEvidenceBaseApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new EarlyEvidenceBaseApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new EarlyEvidenceBaseApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 2.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Author model constructor.
     * @property {module:model/Author}
     */
    Author,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The PagingInfo model constructor.
     * @property {module:model/PagingInfo}
     */
    PagingInfo,

    /**
     * The Paper model constructor.
     * @property {module:model/Paper}
     */
    Paper,

    /**
     * The ReviewingServiceCollection model constructor.
     * @property {module:model/ReviewingServiceCollection}
     */
    ReviewingServiceCollection,

    /**
     * The ReviewingServiceCollectionInner model constructor.
     * @property {module:model/ReviewingServiceCollectionInner}
     */
    ReviewingServiceCollectionInner,

    /**
     * The ReviewingServiceDescription model constructor.
     * @property {module:model/ReviewingServiceDescription}
     */
    ReviewingServiceDescription,

    /**
    * The PaperDetailsApi service constructor.
    * @property {module:api/PaperDetailsApi}
    */
    PaperDetailsApi,

    /**
    * The ReviewingServicesApi service constructor.
    * @property {module:api/ReviewingServicesApi}
    */
    ReviewingServicesApi
};
