http:
  routers:
    # web-admin:
    #   rule: "PathPrefix(`/admin`)"
    #   priority: 2
    #   entryPoints:
    #     - web
    #   middlewares:
    #     - embo-intranet-ipwhitelist
    #     - csrf
    #   service: django

          #api-router:
          #  # rule: "Host(`0.0.0.0`)"
          #  # rule: "PathPrefix(`/api`)"
          #  rule: "( Host(`0.0.0.0`) || Host(`ec2-3-125-193-124.eu-central-1.compute.amazonaws.com`) || Host(`covid19.sourcedata.io`) )  && PathPrefix(`/api`)"
          #  # priority: 1
          #  entryPoints:
          #    - web
          #  middlewares:
          #    # - redirect
          #    - csrf
          #  service: flask

    sd2embo:
      rule: "Host(`{{env "EEB_HOSTNAME_OLD" }}`)"
      entryPoints:
        - web
        - web-secure
      middlewares:
        - redirectToEmbo
      service:
        - vuejs
   
    vuejs-router:
      rule: "Host(`0.0.0.0`) || Host(`{{env "EEB_HOSTNAME" }}`) "
      # priority: 1
      entryPoints:
        - web
      middlewares:
        - redirect
        # - csrf
      service: vuejs

    web-secure-vuejs-router:
      rule: "Host(`{{env "EEB_HOSTNAME" }}`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
        - test-compress
      service: vuejs
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
    web-secure-api-router:
      rule: "( Host(`{{env "EEB_HOSTNAME" }}`) )  && (PathPrefix(`/api`) || PathPrefix(`/sitemap.xml`) || PathPrefix(`/doi/10.1101/067876`) || PathPrefix(`/doi/10.1101/138537`) || PathPrefix(`/doi/10.1101/2021.09.22.461393`) || PathPrefix(`/doi/10.1101/2022.04.08.487678`))"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
        - test-compress
      service: flask
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt


  middlewares:
    redirectToEmbo:
      redirectRegex:
        regex: "https?://{{env "EEB_HOSTNAME_OLD" }}/(.*)"
        replacement: "http://{{env "EEB_HOSTNAME" }}/${1}"
        # permanent: true
    redirect:
      # https://docs.traefik.io/master/middlewares/redirectscheme/
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ['X-CSRFToken']
    test-compress:
      compress: {}
    # embo-intranet-ipwhitelist:
    #   ipWhiteList:
    #     sourceRange:
    #       # - "0.0.0.0/0" # enable this if you want to test "production" on  you local machine
    #       - "172.21.0.0/16"
    #     ipStrategy:
    #       depth: 1
    #     # ipStrategy:
    #     #   excludedIPs:
    #     #     - "192.168.0.101"

  services:
    flask:
      loadBalancer:
        servers:
          - url: http://flask:5000
    vuejs:
      loadBalancer:
        servers:
          - url: http://vuejs
