/*
 * Early Evidence Base API
 * Read-only API for the Early Evidence Base platform providing collections of papers by reviewing service, automagic, and auto topics, as well as details on papers by DOI.
 *
 * OpenAPI spec version: 2.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ReviewingServiceCollection} from '../model/ReviewingServiceCollection';

/**
* ReviewingServices service.
* @module api/ReviewingServicesApi
* @version 2.0.0
*/
export class ReviewingServicesApi {

    /**
    * Constructs a new ReviewingServicesApi. 
    * @alias module:api/ReviewingServicesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the reviewingServicesGet operation.
     * @callback moduleapi/ReviewingServicesApi~reviewingServicesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ReviewingServiceCollection{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get information about available reviewing services
     * @param {module:api/ReviewingServicesApi~reviewingServicesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    reviewingServicesGet(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ReviewingServiceCollection;

      return this.apiClient.callApi(
        '/reviewing_services/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}