name: Docker Image CI

on:
  push:
    branches: ['dev', 'github-actions-setup']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_REVISION: https://github.com/source-data/sd-graph
  IMAGE_SOURCE: ${{ GITHUB_SHA }}
  IMAGE_TAG: dev

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    - name: Build the Docker images
      run: docker-compose -f production.yml -f .github/workflows/docker-compose.yml build

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker images
      run: docker-compose -f production.yml -f .github/workflows/docker-compose.yml push
