name: Docker Image CI

on:
  push:
    branches: ['master', 'dev', 'github-actions-setup']

env:
  REGISTRY: ghcr.io
  IMAGE_SOURCE: https://github.com/source-data/sd-graph
  IMAGE_REVISION: ${{ github.sha }}
  IMAGE_TAG: ${{ github.ref_name }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build the Docker images
      run: docker-compose -f docker-compose.ci.yml build

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the Docker images
      run: docker-compose -f docker-compose.ci.yml push
