# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linting & Testing

on: push

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-cache
    - run: pip install -r requirements/ci.txt
    - run: ruff check .
    - run: flake8 check .
    - run: black --check .
    - run: scripts/lint.sh

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install -y zsh
    - run: cp .env.ci .env
    - run: scripts/run-tests.sh -vv
